apisix:
  node_listen: 9080
  enable_admin: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugin_attr:
  opentelemetry:
    resource:
      service.name: apisix
      service.version: "3.9.1"
    collector:
      address: otel-collector:4318
      request_timeout: 3
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 16

plugins:
  - request-id
  - limit-count
  - opentelemetry
